<a href="https://colab.research.google.com/github/SSR-ds/Learning-DS-and-Algorithms/blob/main/1D_%26_2D_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from array import *

In [2]:
#Creating array and traversing
array_p = array('i',[1,2,3,4,5,6,7,8,9])

In [3]:
def traverse(array):
  for i in array:
    print(i)

In [4]:
traverse(array_p)

1
2
3
4
5
6
7
8
9


In [5]:
#Access individual elements through indexes
array_p[5]

6

In [6]:
array_p.append(10)

In [7]:
array_p

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [8]:
array_p.insert(0,2)

In [9]:
array_p

array('i', [2, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [10]:
array_q =array('i',[11,12,13,14,15,16,17])

In [11]:
array_p.extend(array_q)

In [12]:
array_p

array('i', [2, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17])

In [13]:
temp_list = [45,55,65]
array_p.fromlist(temp_list)
array_p

array('i', [2, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 45, 55, 65])

In [14]:
array_p.remove(65)

In [15]:
array_p

array('i', [2, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 45, 55])

In [16]:
array_p.pop()

55

In [17]:
array_p

array('i', [2, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 45])

In [18]:
array_p.index(45)

18

In [19]:
array_p.reverse()

In [20]:
array_p

array('i', [45, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 2])

In [21]:
array_p.buffer_info()

(140456479772096, 19)

In [22]:
array_p.count(45)

1

In [23]:
array_p.tostring()

b'-\x00\x00\x00\x11\x00\x00\x00\x10\x00\x00\x00\x0f\x00\x00\x00\x0e\x00\x00\x00\r\x00\x00\x00\x0c\x00\x00\x00\x0b\x00\x00\x00\n\x00\x00\x00\t\x00\x00\x00\x08\x00\x00\x00\x07\x00\x00\x00\x06\x00\x00\x00\x05\x00\x00\x00\x04\x00\x00\x00\x03\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00'

In [24]:
array_p.tolist()

[45, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 2]

In [25]:
array_p[1:4]

array('i', [17, 16, 15])

In [26]:
import numpy as np

In [27]:
twod = np.array(([11,12,13,14],[10,11,12,13],[24,25,26,27],[25,26,27,28]))

In [28]:
twod

array([[11, 12, 13, 14],
       [10, 11, 12, 13],
       [24, 25, 26, 27],
       [25, 26, 27, 28]])

In [29]:
new_two_d = np.insert(twod,0, [[1,2,3,4]], axis=1)

In [30]:
new_two_d

array([[ 1, 11, 12, 13, 14],
       [ 2, 10, 11, 12, 13],
       [ 3, 24, 25, 26, 27],
       [ 4, 25, 26, 27, 28]])

In [33]:
new_two_d2 = np.insert(twod,2, [[1,2,3,4]], axis=0)

In [34]:
new_two_d2

array([[11, 12, 13, 14],
       [10, 11, 12, 13],
       [ 1,  2,  3,  4],
       [24, 25, 26, 27],
       [25, 26, 27, 28]])

In [39]:
new_two_d2[0][3]

14

In [40]:
def arrayindexprint(array,rowindex,columnindex):
  if rowindex >= len(array) and columnindex >= len(array[0]):
    print('does not exist')
  else:
    print (array[rowindex][columnindex])

In [42]:
arrayindexprint(new_two_d2,0,3)  

14


In [44]:
def traversal(array):
  for i in range(len(array)):
    for j in range(len(array[0])):
      print(array[i][j])

In [45]:
traversal(new_two_d2)

11
12
13
14
10
11
12
13
1
2
3
4
24
25
26
27
25
26
27
28


In [53]:
def search(array, value):
  for i in range(len(array)):
    for j in range(len(array[0])):
      if array[i][j]==value:
        return str(i)+""+str(j)
      else:
        return 'does not exist'

In [54]:
search(new_two_d2, 99)

'does not exist'

In [55]:
array_p

array('i', [45, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 2])

In [62]:
def delete_1(array,value):
  count=0
  new_array=[]
  for i in array:
    if i != value:
      new_array.insert(count,i)
      count=count+1
  return new_array

In [63]:
delete_1(array_p,2)

[45, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 1]

In [65]:
new_after_deleted = np.delete(new_two_d2,1,axis=1)

In [66]:
new_after_deleted

array([[11, 13, 14],
       [10, 12, 13],
       [ 1,  3,  4],
       [24, 26, 27],
       [25, 27, 28]])